Fix for compiler errors due to project-supplied AST transform failures
AssertionError (failed assert statements)
LinkageError (things like NoClassDefFoundError and NoSuchMethodError)

Also removed redundant " @ line x column y." from the messages.